### ISSUE TITLE
KrakenD RabbitMq interaction

### ISSUE THREAD

**Issue by rmfjd78** [devopsfaith/krakend-pubsub#9]
Hi 

                I’m trying to connect one API published in Krakkend with RabbitMQ and I’m having some errors (page not found) that I think that is related with the my exchange in RabbitMQ.

                My configuration in Krakkend related with the backend is this:

"host": ["amqp://"],
"disable_host_sanitize": true,
"extra_config": {
    "github.com/devopsfaith/krakend-pubsub/subscriber": {
    "subscription_url": "amqp://API_ComunicacaoAutomatica"
    }
},
      I already have a envvar in the server with the host of the RabbitMQ. (RABBIT_SERVER_URL='xxx:xxx@COFPTDRABBITMQ:5672')
                Can you help me in this problem?

Best regards,

**Comment by kpacha** [comment]
please, check out the documentation, your host and subscription_url params are incorrect: https://www.krakend.io/docs/backends/pubsub/#rabbitmq
